version: "3"

services:
  notebook:
    build: .
    image: ml_dev
    volumes:
      - C:/Users/ortiz/Developer/End2End_ML_V3/.:/home/
    ports:
      - 8888:8888
    container_name: ml_development

  backend:
    #restart: always
    container_name: backend
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - 5000:5000
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - FLASK_DEBUG=1

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000